import { Bot } from "./types";

export const bots: Bot[] = [
  // Customer Support bots (proj-1)
  {
    id: "bot-1",
    projectId: "proj-1",
    workspaceId: "ws-1",
    name: "Ticket Classifier",
    description: "Automatically classifies and routes support tickets",
    createdAt: "2024-02-05T10:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-1",
      name: "Classifier Budget",
      balance: 3000,
      limit: 5000,
      currency: "USD",
      lastFourDigits: "0001",
      expiryDate: "06/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-1",
      name: "Daily Classifier Budget",
      allocated: 500,
      spent: 320,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 12500,
    requestsToday: 1250,
    requestsTotal: 145000,
    model: "gpt-4o",
  },
  {
    id: "bot-2",
    projectId: "proj-1",
    workspaceId: "ws-1",
    name: "FAQ Responder",
    description: "Answers common customer questions automatically",
    createdAt: "2024-02-10T14:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-2",
      name: "FAQ Budget",
      balance: 4500,
      limit: 6000,
      currency: "USD",
      lastFourDigits: "0002",
      expiryDate: "06/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-2",
      name: "Daily FAQ Budget",
      allocated: 400,
      spent: 280,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 15200,
    requestsToday: 2100,
    requestsTotal: 230000,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-3",
    projectId: "proj-1",
    workspaceId: "ws-1",
    name: "Sentiment Analyzer",
    description: "Analyzes customer sentiment in real-time",
    createdAt: "2024-02-20T09:00:00Z",
    status: "paused",
    vault: {
      id: "vault-bot-3",
      name: "Sentiment Budget",
      balance: 2200,
      limit: 4000,
      currency: "USD",
      lastFourDigits: "0003",
      expiryDate: "06/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-3",
      name: "Daily Sentiment Budget",
      allocated: 300,
      spent: 0,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 8500,
    requestsToday: 0,
    requestsTotal: 89000,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-4",
    projectId: "proj-1",
    workspaceId: "ws-1",
    name: "Escalation Handler",
    description: "Handles complex escalated tickets",
    createdAt: "2024-03-01T11:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-4",
      name: "Escalation Budget",
      balance: 2800,
      limit: 5000,
      currency: "USD",
      lastFourDigits: "0004",
      expiryDate: "06/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-4",
      name: "Daily Escalation Budget",
      allocated: 350,
      spent: 210,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 9000,
    requestsToday: 450,
    requestsTotal: 52000,
    model: "gpt-4o",
  },
  // Sales Assistant bots (proj-2)
  {
    id: "bot-5",
    projectId: "proj-2",
    workspaceId: "ws-1",
    name: "Lead Qualifier",
    description: "Qualifies incoming leads automatically",
    createdAt: "2024-03-20T10:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-5",
      name: "Lead Budget",
      balance: 3200,
      limit: 5000,
      currency: "USD",
      lastFourDigits: "0005",
      expiryDate: "09/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-5",
      name: "Daily Lead Budget",
      allocated: 400,
      spent: 310,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 14500,
    requestsToday: 890,
    requestsTotal: 98000,
    model: "gpt-4o",
  },
  {
    id: "bot-6",
    projectId: "proj-2",
    workspaceId: "ws-1",
    name: "Proposal Writer",
    description: "Generates customized sales proposals",
    createdAt: "2024-04-01T14:00:00Z",
    status: "error",
    vault: {
      id: "vault-bot-6",
      name: "Proposal Budget",
      balance: 2500,
      limit: 5000,
      currency: "USD",
      lastFourDigits: "0006",
      expiryDate: "09/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-6",
      name: "Daily Proposal Budget",
      allocated: 350,
      spent: 0,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 9800,
    requestsToday: 0,
    requestsTotal: 34000,
    model: "gpt-4o",
  },
  {
    id: "bot-7",
    projectId: "proj-2",
    workspaceId: "ws-1",
    name: "Follow-up Bot",
    description: "Sends personalized follow-up messages",
    createdAt: "2024-04-15T09:00:00Z",
    status: "needs_setup",
    vault: {
      id: "vault-bot-7",
      name: "Follow-up Budget",
      balance: 3000,
      limit: 4000,
      currency: "USD",
      lastFourDigits: "0007",
      expiryDate: "09/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-7",
      name: "Daily Follow-up Budget",
      allocated: 250,
      spent: 0,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 7800,
    requestsToday: 0,
    requestsTotal: 45000,
    model: "gpt-4o-mini",
  },
  // Content Generation bots (proj-3)
  {
    id: "bot-8",
    projectId: "proj-3",
    workspaceId: "ws-1",
    name: "Blog Writer",
    description: "Generates SEO-optimized blog posts",
    createdAt: "2024-04-05T10:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-8",
      name: "Blog Budget",
      balance: 1800,
      limit: 3500,
      currency: "USD",
      lastFourDigits: "0008",
      expiryDate: "11/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-8",
      name: "Daily Blog Budget",
      allocated: 200,
      spent: 145,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 11200,
    requestsToday: 120,
    requestsTotal: 28000,
    model: "gpt-4o",
  },
  {
    id: "bot-9",
    projectId: "proj-3",
    workspaceId: "ws-1",
    name: "Social Media Bot",
    description: "Creates social media content",
    createdAt: "2024-04-10T14:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-9",
      name: "Social Budget",
      balance: 1600,
      limit: 3000,
      currency: "USD",
      lastFourDigits: "0009",
      expiryDate: "11/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-9",
      name: "Daily Social Budget",
      allocated: 150,
      spent: 98,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 9500,
    requestsToday: 340,
    requestsTotal: 82000,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-10",
    projectId: "proj-3",
    workspaceId: "ws-1",
    name: "Email Copywriter",
    description: "Writes marketing emails",
    createdAt: "2024-04-20T09:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-10",
      name: "Email Budget",
      balance: 1400,
      limit: 2500,
      currency: "USD",
      lastFourDigits: "0010",
      expiryDate: "11/26",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-10",
      name: "Daily Email Budget",
      allocated: 120,
      spent: 85,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 8000,
    requestsToday: 280,
    requestsTotal: 65000,
    model: "gpt-4o-mini",
  },
  // Data Analysis bots (proj-4)
  {
    id: "bot-11",
    projectId: "proj-4",
    workspaceId: "ws-1",
    name: "Report Generator",
    description: "Creates automated data reports",
    createdAt: "2024-05-15T10:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-11",
      name: "Report Budget",
      balance: 4000,
      limit: 6000,
      currency: "USD",
      lastFourDigits: "0011",
      expiryDate: "02/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-11",
      name: "Daily Report Budget",
      allocated: 300,
      spent: 220,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 13500,
    requestsToday: 85,
    requestsTotal: 18000,
    model: "gpt-4o",
  },
  {
    id: "bot-12",
    projectId: "proj-4",
    workspaceId: "ws-1",
    name: "Insights Bot",
    description: "Extracts insights from data sets",
    createdAt: "2024-05-20T14:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-12",
      name: "Insights Budget",
      balance: 3500,
      limit: 5500,
      currency: "USD",
      lastFourDigits: "0012",
      expiryDate: "02/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-12",
      name: "Daily Insights Budget",
      allocated: 280,
      spent: 195,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 9000,
    requestsToday: 65,
    requestsTotal: 12000,
    model: "gpt-4o",
  },
  // Personal Projects bots (proj-5, proj-6)
  {
    id: "bot-13",
    projectId: "proj-5",
    workspaceId: "ws-2",
    name: "Article Writer",
    description: "Writes personal blog articles",
    createdAt: "2024-04-05T16:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-13",
      name: "Article Budget",
      balance: 400,
      limit: 800,
      currency: "USD",
      lastFourDigits: "0013",
      expiryDate: "04/26",
      type: "credit",
    },
    budget: {
      id: "budget-bot-13",
      name: "Daily Article Budget",
      allocated: 20,
      spent: 12,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 450,
    requestsToday: 15,
    requestsTotal: 3200,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-14",
    projectId: "proj-5",
    workspaceId: "ws-2",
    name: "Editor Bot",
    description: "Edits and improves writing",
    createdAt: "2024-04-10T10:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-14",
      name: "Editor Budget",
      balance: 350,
      limit: 600,
      currency: "USD",
      lastFourDigits: "0014",
      expiryDate: "04/26",
      type: "credit",
    },
    budget: {
      id: "budget-bot-14",
      name: "Daily Editor Budget",
      allocated: 15,
      spent: 8,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 330,
    requestsToday: 22,
    requestsTotal: 4500,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-15",
    projectId: "proj-6",
    workspaceId: "ws-2",
    name: "Code Helper",
    description: "Assists with coding tasks",
    createdAt: "2024-05-20T10:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-15",
      name: "Code Budget",
      balance: 500,
      limit: 900,
      currency: "USD",
      lastFourDigits: "0015",
      expiryDate: "07/26",
      type: "credit",
    },
    budget: {
      id: "budget-bot-15",
      name: "Daily Code Budget",
      allocated: 25,
      spent: 18,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 460,
    requestsToday: 45,
    requestsTotal: 8900,
    model: "gpt-4o",
  },
  // StartupXYZ bots (proj-7, proj-8, proj-9)
  {
    id: "bot-16",
    projectId: "proj-7",
    workspaceId: "ws-3",
    name: "Welcome Bot",
    description: "Welcomes new users",
    createdAt: "2024-06-20T09:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-16",
      name: "Welcome Budget",
      balance: 1500,
      limit: 3000,
      currency: "USD",
      lastFourDigits: "0016",
      expiryDate: "01/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-16",
      name: "Daily Welcome Budget",
      allocated: 150,
      spent: 95,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 5800,
    requestsToday: 320,
    requestsTotal: 45000,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-17",
    projectId: "proj-7",
    workspaceId: "ws-3",
    name: "Tutorial Guide",
    description: "Guides users through tutorials",
    createdAt: "2024-06-25T14:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-17",
      name: "Tutorial Budget",
      balance: 1200,
      limit: 2500,
      currency: "USD",
      lastFourDigits: "0017",
      expiryDate: "01/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-17",
      name: "Daily Tutorial Budget",
      allocated: 120,
      spent: 78,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 5200,
    requestsToday: 180,
    requestsTotal: 32000,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-18",
    projectId: "proj-7",
    workspaceId: "ws-3",
    name: "Setup Assistant",
    description: "Helps with account setup",
    createdAt: "2024-07-01T11:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-18",
      name: "Setup Budget",
      balance: 1100,
      limit: 2200,
      currency: "USD",
      lastFourDigits: "0018",
      expiryDate: "01/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-18",
      name: "Daily Setup Budget",
      allocated: 100,
      spent: 65,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 4800,
    requestsToday: 145,
    requestsTotal: 28000,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-19",
    projectId: "proj-8",
    workspaceId: "ws-3",
    name: "Feedback Analyzer",
    description: "Analyzes customer feedback",
    createdAt: "2024-07-05T09:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-19",
      name: "Feedback Budget",
      balance: 1800,
      limit: 3500,
      currency: "USD",
      lastFourDigits: "0019",
      expiryDate: "05/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-19",
      name: "Daily Feedback Budget",
      allocated: 140,
      spent: 92,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 8200,
    requestsToday: 210,
    requestsTotal: 38000,
    model: "gpt-4o",
  },
  {
    id: "bot-20",
    projectId: "proj-8",
    workspaceId: "ws-3",
    name: "Survey Bot",
    description: "Conducts automated surveys",
    createdAt: "2024-07-10T14:00:00Z",
    status: "paused",
    vault: {
      id: "vault-bot-20",
      name: "Survey Budget",
      balance: 1500,
      limit: 2500,
      currency: "USD",
      lastFourDigits: "0020",
      expiryDate: "05/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-20",
      name: "Daily Survey Budget",
      allocated: 100,
      spent: 0,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 6000,
    requestsToday: 0,
    requestsTotal: 22000,
    model: "gpt-4o-mini",
  },
  {
    id: "bot-21",
    projectId: "proj-9",
    workspaceId: "ws-3",
    name: "Metrics Bot",
    description: "Tracks and reports metrics",
    createdAt: "2024-08-05T11:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-21",
      name: "Metrics Budget",
      balance: 1400,
      limit: 2800,
      currency: "USD",
      lastFourDigits: "0021",
      expiryDate: "08/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-21",
      name: "Daily Metrics Budget",
      allocated: 120,
      spent: 85,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 6800,
    requestsToday: 95,
    requestsTotal: 18000,
    model: "gpt-4o",
  },
  {
    id: "bot-22",
    projectId: "proj-9",
    workspaceId: "ws-3",
    name: "Trend Analyzer",
    description: "Identifies trends in data",
    createdAt: "2024-08-10T09:00:00Z",
    status: "active",
    vault: {
      id: "vault-bot-22",
      name: "Trend Budget",
      balance: 1200,
      limit: 2400,
      currency: "USD",
      lastFourDigits: "0022",
      expiryDate: "08/27",
      type: "virtual",
    },
    budget: {
      id: "budget-bot-22",
      name: "Daily Trend Budget",
      allocated: 110,
      spent: 72,
      currency: "USD",
      period: "daily",
    },
    totalSpend: 5500,
    requestsToday: 78,
    requestsTotal: 14000,
    model: "gpt-4o",
  },
];

export function getBot(id: string): Bot | undefined {
  return bots.find((b) => b.id === id);
}

export function getBotsByProject(projectId: string): Bot[] {
  return bots.filter((b) => b.projectId === projectId);
}

export function getBotsByWorkspace(workspaceId: string): Bot[] {
  return bots.filter((b) => b.workspaceId === workspaceId);
}

export function getBotStatusCounts() {
  return {
    active: bots.filter((b) => b.status === "active").length,
    paused: bots.filter((b) => b.status === "paused").length,
    error: bots.filter((b) => b.status === "error").length,
    needs_setup: bots.filter((b) => b.status === "needs_setup").length,
  };
}

