import { Project } from "./types";

export const projects: Project[] = [
  // Acme Corp Projects
  {
    id: "proj-1",
    workspaceId: "ws-1",
    name: "Customer Support",
    description: "AI-powered customer support automation",
    createdAt: "2024-02-01T10:00:00Z",
    vault: {
      id: "vault-proj-1",
      name: "Support Budget",
      balance: 12000,
      limit: 20000,
      currency: "USD",
      lastFourDigits: "5678",
      expiryDate: "06/26",
      type: "virtual",
    },
    budget: {
      id: "budget-proj-1",
      name: "Monthly Support Budget",
      allocated: 15000,
      spent: 11200,
      currency: "USD",
      period: "monthly",
    },
    botCount: 4,
    totalSpend: 45200,
    status: "active",
  },
  {
    id: "proj-2",
    workspaceId: "ws-1",
    name: "Sales Assistant",
    description: "Lead qualification and sales automation",
    createdAt: "2024-03-15T14:00:00Z",
    vault: {
      id: "vault-proj-2",
      name: "Sales Budget",
      balance: 8500,
      limit: 15000,
      currency: "USD",
      lastFourDigits: "9012",
      expiryDate: "09/26",
      type: "virtual",
    },
    budget: {
      id: "budget-proj-2",
      name: "Monthly Sales Budget",
      allocated: 12000,
      spent: 8900,
      currency: "USD",
      period: "monthly",
    },
    botCount: 3,
    totalSpend: 32100,
    status: "active",
  },
  {
    id: "proj-3",
    workspaceId: "ws-1",
    name: "Content Generation",
    description: "Marketing content and copy generation",
    createdAt: "2024-04-01T09:00:00Z",
    vault: {
      id: "vault-proj-3",
      name: "Content Budget",
      balance: 5000,
      limit: 10000,
      currency: "USD",
      lastFourDigits: "3456",
      expiryDate: "11/26",
      type: "virtual",
    },
    budget: {
      id: "budget-proj-3",
      name: "Monthly Content Budget",
      allocated: 8000,
      spent: 5200,
      currency: "USD",
      period: "monthly",
    },
    botCount: 3,
    totalSpend: 28700,
    status: "active",
  },
  {
    id: "proj-4",
    workspaceId: "ws-1",
    name: "Data Analysis",
    description: "Automated data analysis and reporting",
    createdAt: "2024-05-10T11:00:00Z",
    vault: {
      id: "vault-proj-4",
      name: "Analysis Budget",
      balance: 7500,
      limit: 12000,
      currency: "USD",
      lastFourDigits: "7890",
      expiryDate: "02/27",
      type: "virtual",
    },
    budget: {
      id: "budget-proj-4",
      name: "Monthly Analysis Budget",
      allocated: 10000,
      spent: 7150,
      currency: "USD",
      period: "monthly",
    },
    botCount: 2,
    totalSpend: 22500,
    status: "active",
  },
  // Personal Projects
  {
    id: "proj-5",
    workspaceId: "ws-2",
    name: "Blog Writer",
    description: "Personal blog content assistant",
    createdAt: "2024-04-01T16:00:00Z",
    vault: {
      id: "vault-proj-5",
      name: "Blog Budget",
      balance: 800,
      limit: 1500,
      currency: "USD",
      lastFourDigits: "1111",
      expiryDate: "04/26",
      type: "credit",
    },
    budget: {
      id: "budget-proj-5",
      name: "Monthly Blog Budget",
      allocated: 200,
      spent: 145,
      currency: "USD",
      period: "monthly",
    },
    botCount: 2,
    totalSpend: 780,
    status: "active",
  },
  {
    id: "proj-6",
    workspaceId: "ws-2",
    name: "Code Assistant",
    description: "Personal coding helper",
    createdAt: "2024-05-15T10:00:00Z",
    vault: {
      id: "vault-proj-6",
      name: "Code Budget",
      balance: 600,
      limit: 1000,
      currency: "USD",
      lastFourDigits: "2222",
      expiryDate: "07/26",
      type: "credit",
    },
    budget: {
      id: "budget-proj-6",
      name: "Monthly Code Budget",
      allocated: 150,
      spent: 98,
      currency: "USD",
      period: "monthly",
    },
    botCount: 1,
    totalSpend: 460,
    status: "active",
  },
  // StartupXYZ Projects
  {
    id: "proj-7",
    workspaceId: "ws-3",
    name: "User Onboarding",
    description: "Automated user onboarding flows",
    createdAt: "2024-06-15T09:00:00Z",
    vault: {
      id: "vault-proj-7",
      name: "Onboarding Budget",
      balance: 4000,
      limit: 8000,
      currency: "USD",
      lastFourDigits: "3333",
      expiryDate: "01/27",
      type: "virtual",
    },
    budget: {
      id: "budget-proj-7",
      name: "Monthly Onboarding Budget",
      allocated: 6000,
      spent: 3200,
      currency: "USD",
      period: "monthly",
    },
    botCount: 3,
    totalSpend: 15800,
    status: "active",
  },
  {
    id: "proj-8",
    workspaceId: "ws-3",
    name: "Product Feedback",
    description: "Customer feedback analysis",
    createdAt: "2024-07-01T14:00:00Z",
    vault: {
      id: "vault-proj-8",
      name: "Feedback Budget",
      balance: 3500,
      limit: 6000,
      currency: "USD",
      lastFourDigits: "4444",
      expiryDate: "05/27",
      type: "virtual",
    },
    budget: {
      id: "budget-proj-8",
      name: "Monthly Feedback Budget",
      allocated: 5000,
      spent: 2800,
      currency: "USD",
      period: "monthly",
    },
    botCount: 2,
    totalSpend: 14200,
    status: "active",
  },
  {
    id: "proj-9",
    workspaceId: "ws-3",
    name: "Analytics Bot",
    description: "Real-time analytics assistant",
    createdAt: "2024-08-01T11:00:00Z",
    vault: {
      id: "vault-proj-9",
      name: "Analytics Budget",
      balance: 2800,
      limit: 5000,
      currency: "USD",
      lastFourDigits: "5555",
      expiryDate: "08/27",
      type: "virtual",
    },
    budget: {
      id: "budget-proj-9",
      name: "Monthly Analytics Budget",
      allocated: 4000,
      spent: 2750,
      currency: "USD",
      period: "monthly",
    },
    botCount: 2,
    totalSpend: 12300,
    status: "active",
  },
];

export function getProject(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}

export function getProjectsByWorkspace(workspaceId: string): Project[] {
  return projects.filter((p) => p.workspaceId === workspaceId);
}

